// Code generated by Alpha Compiler v1.0
// DO NOT EDIT

package main

// Global variables
var (
	sum     int
	message string
)

func soma(a int, b int) int {
	var t0 int

	t0 = a + b
	return t0
}

func init() {
	var t0 interface{}

	t0 = soma(5, 10)
	sum = t0
	message = t1
	return
}

func isOldEnough(age int) bool {
	var t0 bool

	t0 = age > 18
	return t0
}

func hello1[T any](msg T) string {
	var t0 int

	t0 = Hello + msg
	return t0
}

func hello2[A any, B any](a A, b B) string {
	var t0 int
	var t1 string

	t0 = a + b
	t1 = fmt.Sprintf("%v", t0)
	return t1
}

func hello3() string {
	return Hello
}
